### ISSUE TITLE
"Exception: static status of index does not match expected column static status" When comparing Frame to FrameGO

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#108]
When comparing `Frame` and `FrameGO`, an exception is raised. 

```python
a = sf.Frame((1, 2, 3))
a == a.to_frame_go()
```

```
Traceback (most recent call last):
  Python Shell, prompt 8, line 1
    # Used internally for debug sandbox under external interpreter
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/container.py", line 295, in func
    return self._ufunc_binary_operator(operator=operator_func, other=other)
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/frame.py", line 2103, in _ufunc_binary_operator
    other_tb = other.reindex(columns=columns, index=index)._blocks
  File "/home/rutherford/.env37/lib/python3.7/site-packages/static_frame/core/frame.py", line 1378, in reindex
    raise Exception('static status of index does not match expected column static status')
builtins.Exception: static status of index does not match expected column static status
```

I think its desirable for these to be comparable, even thought they're different types.

**Comment by flexatone** [comment]
Thank you for isolating this issue. This has been fixed and will be release as part of 0.4.3.

```python
In [2]: a = sf.Frame((1, 2, 3))                                                           

In [3]: a == a.to_frame_go()                                                              
Out[3]: 
<FrameGO>
<IndexGO> 0      <int64>
<Index>
0         True
1         True
2         True
```
