### ISSUE TITLE
Frame bloc assignment fails if target frame is a FrameGO

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#196]
bloc assignments fail if the assignment frame is a normal `Frame` but the target frame is a `FrameGO`.
```
>>> f = sf.Frame.from_records(np.arange(9).reshape(3,3))
>>> fgo = f.to_frame_go()
>>> f.assign.bloc[f % 2 == 0](-f)
<Frame>
<Index> 0       1       2       <int64>
<Index>
0       0       1       -2
1       3       -4      5
2       -6      7       -8
<int64> <int64> <int64> <int64>
>>> f.assign.bloc[f % 2 == 0](-fgo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.7/site-packages/static_frame/core/frame.py", line 5060, in __call__
    fill_value=invalid
  File ".../lib/python3.7/site-packages/static_frame/core/frame.py", line 2395, in reindex
    columns_constructor = columns._IMMUTABLE_CONSTRUCTOR
AttributeError: 'Index' object has no attribute '_IMMUTABLE_CONSTRUCTOR'
```

The other combinations succeed (`FrameGO` -> `FrameGO`, `FrameGO` -> `Frame`)
```python
succeeds = fgo.assign.bloc[f % 2 == 0](-fgo) 
succeeds = fgo.assign.bloc[f % 2 == 0](-f) 
```

**Comment by flexatone** [comment]
Many thanks for isolating this issue. 

The logic in `Frame.reindex` for managing moves between mutable and immutable indices on columns was incomplete. I had implemented a new function, used elsewhere, that handles these cases correctly. The fix here involved simply using that function, which is a nice improvement.

This fix will be part of the 0.6.10 release.
