### ISSUE TITLE
Frame.iter_group* raises an error when empty

### ISSUE THREAD

**Issue by nekobon** [InvestmentSystems/static-frame#269]
I noticed that when a Frame is empty, both `iter_group` and `iter_group_items` raise an `IndexError`. It would be nice if it is instead no-op like other `iter_*` methods. 

Current Behavior

```python
>>> import static_frame as sf
>>> f = sf.Frame.from_element(1, columns=[1,2,3], index=['a'])
>>> empty = f.reindex([])   # 3 columns with no row
>>> for x in empty.iter_element(): # no-op without error
...     print(x)
... 
>>> for x in empty.iter_group(key=1): # raises IndexError
...     print(x)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tomita/.env38/lib/python3.8/site-packages/static_frame/core/node_iter.py", line 373, in __iter__
    yield from self._func_values()
  File "/home/tomita/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 3985, in _axis_group_loc
    yield from (x for _, x in self._axis_group_loc_items(key=key, axis=axis))
  File "/home/tomita/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 3985, in <genexpr>
    yield from (x for _, x in self._axis_group_loc_items(key=key, axis=axis))
  File "/home/tomita/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 3971, in _axis_group_loc_items
    yield from self._axis_group_sort_items(key=key,
  File "/home/tomita/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 3924, in _axis_group_sort_items
    group: tp.Hashable = get_group(0)
  File "/home/tomita/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 3917, in get_group
    return frame_sorted.iloc[i, iloc_key]
  File "/home/tomita/.env38/lib/python3.8/site-packages/static_frame/core/node_selector.py", line 43, in __getitem__
    return self._func(key)
  File "/home/tomita/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 3461, in _extract_iloc
    return self._extract(*key)
  File "/home/tomita/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 3378, in _extract
    blocks = self._blocks._extract(row_key=row_key, column_key=column_key)
  File "/home/tomita/.env38/lib/python3.8/site-packages/static_frame/core/type_blocks.py", line 1859, in _extract
    return b[row_key, column] # return single item
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Expected Behavior

```python
>>> for x in empty.iter_group(key=1):  # no IndexError
...     print(x)
... 
>>>
```

**Comment by flexatone** [comment]
Many thanks for isolating this issue. This has been fixed and will be included in the 0.7.3 release.
