### ISSUE TITLE
sf.Frame.from_overlay with FrameGO arguments fails 

### ISSUE THREAD

**Issue by gettodaze** [InvestmentSystems/static-frame#385]
**Description**

I just came across some behavior that I wasn't expecting. It might be desired, but I thought I would double-check.
Is it expected that `sf.Frame.from_overlay` fails when given two `FrameGOs`, and `sf.FrameGO.from_overlay` should be used instead?

**Example**

Provide an interactive Python session, or Python code, to demonstrate the issue. Please keep example data to a minimum.

```python
>>> fgo = sf.FrameGO.from_element('a', index=[1,2,3,4], columns = list('abcd'))
>>> fgo_b = sf.FrameGO.from_element('b', index=[1,2,3,4], columns = list('abcd'))

fails:
>>> sf.Frame.from_overlay((fgo, fgo_b))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mccloskey/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 632, in from_overlay
    post = container.reindex(
  File "/home/mccloskey/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 3327, in reindex
    return self.__class__(
  File "/home/mccloskey/.env38/lib/python3.8/site-packages/static_frame/core/frame.py", line 2746, in __init__
    raise ErrorInitFrame(f'supplied column constructor does not match required static attribute: {self._COLUMNS_CONSTRUCTOR.STATIC}')
static_frame.core.exception.ErrorInitFrame: supplied column constructor does not match required static attribute: False

succeeds:
>>> sf.FrameGO.from_overlay((fgo, fgo_b))
<FrameGO>
<IndexGO> a     b     c     d     <<U1>
<Index>
1         a     a     a     a
2         a     a     a     a
3         a     a     a     a
4         a     a     a     a
<int64>   <<U1> <<U1> <<U1> <<U1>
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
In [8]: sf.Platform.display()                                                   
Out[8]: 
<Series: platform>
<Index>
platform           Linux-5.4.0-87-generic-x86_64-with-glibc2.27
sys.version        3.8.12 (default, Sep 15 2021, 13:10:50) [GCC 7.5.0]
static-frame       0.8.20
numpy              1.17.4
pandas             0.24.2
xlsxwriter         1.1.5
openpyxl           2.5.4
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            <ModuleNotFoundError>
msgpack_numpy      <ModuleNotFoundError>
<<U13>             <object>

```

**Comment by flexatone** [comment]
Many thanks for isolating this issue. This is not expected and has been corrected. The fix will be part of the 0.8.21 release.
