### ISSUE TITLE
`Frame.set_index_hierarchy` fails for `Frame`s with only one row

### ISSUE THREAD

**Issue by CrepeGoat** [InvestmentSystems/static-frame#50]
For examples:
```python
sf.Frame.from_records([
    ('one', 1, 'hello'),
    ('two', 2, 'cya'),
], columns=['name', 'val', 'msg']).set_index_hierarchy(['name', 'val'], drop=True)
```
(correctly afaik) produces this frame:
```
<Frame>
<Index>                       msg   <<U4>
<Index...
one                  1        hello
two                  2        cya
<object>             <object> <<U5>
```

But if I remove the second row, like so:
```python
sf.Frame.from_records([
    ('one', 1, 'hello'),
], columns=['name', 'val', 'msg']).set_index_hierarchy(['name', 'val'], drop=True)
```
this fails with the following traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/static_frame/core/frame.py", line 2083, in set_index_hierarchy
    index = IndexHierarchy.from_labels(index_labels, name=column_name)
  File "/usr/local/lib/python3.5/dist-packages/static_frame/core/index_hierarchy.py", line 586, in from_labels
    for d, v in enumerate(label):
TypeError: 'int' object is not iterable
```

One detail to note is that it seems to fail on the first non-iterable `set_index_hierarchy` column value; it just so happens that the first is 'one' which is iterable.

Is this in some way an intended behavior?

**Comment by flexatone** [comment]
Thanks for isolating this edge case! This is not intended; I will take a look and push a fix soon.

**Comment by flexatone** [comment]
This is now fixed, and I will close this issue with my next push. Fixing this uncovered a few places where the underlying `TypeBlocks` was not always consistent in handling the dimensions of returned arrays.

```python
>>> sf.Frame.from_records([
...     ('one', 1, 'hello'),
... ], columns=['name', 'val', 'msg']).set_index_hierarchy(['name', 'val'], drop=True)
<Frame>
<Index>                       msg   <<U4>
<Index...
one                  1        hello
<object>             <object> <<U5>
```
