### ISSUE TITLE
Using `header_is_columns` on `sf.Frame.from_csv` causes exception

### ISSUE THREAD

**Issue by ThatsGobbles** [InvestmentSystems/static-frame#54]
A minimal example:

```python
from io import StringIO

import static_frame as sf

INPUT_STR = '''
196412	0.0
196501	0.0
196502	0.0
196503	0.0
196504	0.0
196505	0.0'''

if __name__ == '__main__':
    works_but_wrong_headers = sf.Frame.from_tsv(StringIO(INPUT_STR), index_column=0)
    desired_but_fails = sf.Frame.from_tsv(StringIO(INPUT_STR), index_column=0, header_is_columns=False)
```

The exception I observe:

```
Traceback (most recent call last):
  File "/home/<username>/sf_test_case.py", line 15, in <module>
    desired_but_fails = sf.Frame.from_tsv(StringIO(INPUT_STR), index_column=0, header_is_columns=False)
  File "/home/<username>/src/rapc/static_frame/static_frame/core/frame.py", line 713, in from_tsv
    return cls.from_csv(fp, delimiter='\t', **kwargs)
  File "/home/<username>/src/rapc/static_frame/static_frame/core/frame.py", line 696, in from_csv
    missing_values={''},
  File "/home/<username>/.env37/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1771, in genfromtxt
    names = list(names)
TypeError: 'bool' object is not iterable
```

**Comment by flexatone** [comment]
Thank you for reporting this issue. The issue here is that the `False` condition for the `header_is_columns` was not being properly handled. This now works as expected.
