### ISSUE TITLE
IndexError when comparing series with different indexes

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#60]
This only happens if I set the index on one of the series, as below.

```python
r = sf.Series(['a', 'b', 'c'])
c = sf.Series(['a', 'b'], index=['a', 'b'])
r == c

Traceback (most recent call last):
  Python Shell, prompt 6, line 3
    pass
  File "/home/rutherford/src/rapc/static_frame/static_frame/core/operator_delegate.py", line 171, in func
    return self._ufunc_binary_operator(operator=operator_func, other=other)
  File "/home/rutherford/src/rapc/static_frame/static_frame/core/series.py", line 716, in _ufunc_binary_operator
    values = self.reindex(index).values
  File "/home/rutherford/src/rapc/static_frame/static_frame/core/series.py", line 433, in reindex
    values[ic.iloc_dst] = self.values[ic.iloc_src]
builtins.IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by ForeverWintr** [comment]
Actually, the issue seems unrelated to series size:

```python
r = sf.Series(['a', 'b'])
c = sf.Series(['a', 'b'], index=['a', 'b'])
r == c
```
Produces the same error.

**Comment by flexatone** [comment]
Thanks for posting this issue!

This is now fixed:
```
>>> import static_frame as sf
>>> r = sf.Series(['a', 'b'])
>>> c = sf.Series(['a', 'b'], index=['a', 'b'])
>>> r == c
<Series>
<Index>
0        False
1        False
a        False
b        False
<object> <bool>
```
