### ISSUE TITLE
Empty Frame `.to_pandas()` fails

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/static-frame#606]
**Example**

```python
>>> import static_frame as sf
>>> sf.Frame().to_pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/venv/lib/python3.8/site-packages/static_frame/core/frame.py", line 7360, in to_pandas
    array = self._blocks._blocks[0].copy()
IndexError: list index out of range
```

**Platform**
```python
>>> import static_frame as sf
>>> sf.Platform.display()
<Series: platform>
<Index>
platform           Linux-5.4.0-125-generic-x86_64-with-glibc2.29
sys.version        3.8.12 (default, Aug 26 2022, 13:23:08) [GCC 9.4.0]
static-frame       0.9.14
numpy              1.19.2
pandas             0.25.3
xlsxwriter         1.1.5
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.6.1
pyarrow            0.17.0
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>

```

**Comment by flexatone** [comment]
Thanks for reporting this; this will be corrected with the merge of the associated PR.
