### ISSUE TITLE
Support Frame construction with columns but no data

### ISSUE THREAD

**Issue by flexatone** [InvestmentSystems/static-frame#65]

**Comment by colinalexander** [comment]
What is the expected behavior?  It appears to already work, but you probably have something else in mind.

```
>>> sf.Frame(((1, 2), (3, 4), (5, 6)), columns=('a', 'b'))
<Frame>
<Index> a       b       <<U1>
<Index>
0       1       2
1       3       4
2       5       6
<int64> <int64> <int64>
```

**Comment by brandtbucher** [comment]
This is the example we discussed offline... an empty frame with only columns and no data.

```py
>>> sf.Frame(columns=("a", "b", "c"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/static_frame/core/frame.py", line 875, in __init__
    raise RuntimeError('cannot create rows when no data given')
RuntimeError: cannot create rows when no data given
```

Currently, the best way is to add a dummy row and drop it:

```py
>>> sf.Frame(None, index=(None,), columns=("a", "b", "c")).drop.iloc[0]
<Frame>
<Index>  a        b        c        <<U1>
<Index>
<object> <object> <object> <object>
```

You're right that this issue could probably benefit from a more descriptive title.
