### ISSUE TITLE
Frame.from_records fails if given dict view objects

### ISSUE THREAD

**Issue by ForeverWintr** [InvestmentSystems/static-frame#75]
Typehinting on `from_records` suggests `records` can be any `Iterable`, but it fails if passed a dict view:

```python
import static_frame as sf
a = {1: {'a': 1, 'b': 2,}, 2: {'a': 4, 'b': 3,}}
sf.Frame.from_records(a.values(), index=list(a.keys()))

Traceback (most recent call last):
  Python Shell, prompt 12, line 1
    # Used internally for debug sandbox under external interpreter
  File "/home/rutherford/src/rapc/static_frame/static_frame/core/frame.py", line 372, in from_records
    return cls(TypeBlocks.from_blocks(block_gen()),
  File "/home/rutherford/src/rapc/static_frame/static_frame/core/type_blocks.py", line 98, in from_blocks
    for block in raw_blocks:
  File "/home/rutherford/src/rapc/static_frame/static_frame/core/frame.py", line 309, in blocks
    row_reference = rows[0]
builtins.TypeError: 'dict_values' object is not subscriptable
```

A similar error occurs on when passing a dict view to the index:

```
sf.Frame.from_records((c for c in a.values()), index=a.keys())

Traceback (most recent call last):
  Python Shell, prompt 17, line 1
    # Used internally for debug sandbox under external interpreter
  File "/home/rutherford/src/rapc/static_frame/static_frame/core/frame.py", line 376, in from_records
    own_data=True)
  File "/home/rutherford/src/rapc/static_frame/static_frame/core/frame.py", line 880, in __init__
    self._index = Index(index)
  File "/home/rutherford/src/rapc/static_frame/static_frame/core/index.py", line 415, in __init__
    if len(self._map) != len(self._labels):
builtins.TypeError: len() of unsized object
```

**Comment by ForeverWintr** [comment]
The issue is this check in the inner `blocks` function in `from_records`:

```
if not hasattr(records, '__len__'):
    rows = list(records)
else:
    rows = records

row_reference = rows[0]

```

A dictview has a len, but can't be indexed into!

**Comment by flexatone** [comment]
Thanks for isolating this case! I will explore some solutions.

**Comment by flexatone** [comment]
`Frame.from_records` has been extended to support iterables that have `__len__` but do not have `__getitem__`, and better, this is done without creating an additional sequence (list or tuple) from those iterables, as we do not need index access to their contents but can simply use iterators derived from those iterables. Thus, no copy of the `dict_values` data is required.

```python
In [1]: import static_frame as sf                                                                                                                            

In [2]: a = {1: {'a': 1, 'b': 2,}, 2: {'a': 4, 'b': 3,}}                                                                                                     

In [3]: sf.Frame.from_records(a.values(), index=list(a.keys()))                                                                                              
Out[3]: 
<Frame>
<Index> a       b       <<U1>
<Index>
1       1       2
2       4       3
<int64> <int64> <int64>
```
