### ISSUE TITLE
Mangled Series when constructed from doubly-nested iterable.

### ISSUE THREAD

**Issue by brandtbucher** [InvestmentSystems/static-frame#93]
```py
>>> import static_frame as sf
>>> s = sf.Series([["cat", "dog"]])
>>> s
<Series>
<Index>
0        'cat' 'dog'
<int64>  <<U3>
>>> s[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bucher/.env37/lib/python3.7/site-packages/static_frame/core/series.py", line 961, in __getitem__
    return self._extract_loc(key)
  File "/home/bucher/.env37/lib/python3.7/site-packages/static_frame/core/series.py", line 953, in _extract_loc
    name=self._name)
  File "/home/bucher/.env37/lib/python3.7/site-packages/static_frame/core/series.py", line 279, in __init__
    if not self._index.STATIC:
AttributeError: 'numpy.int64' object has no attribute 'STATIC'
```

I haven't looked into it, I'm _guessing_ it's due to shared `Series` / `Frame` construction code... perhaps `static_frame.core.util.iterable_to_array`?

**Comment by flexatone** [comment]
Thanks for isolating this issue!

This exposed a few potential problems in initialization of `Series` & `Frame`, which have no been handled:

1. `Series` now explicitly fails if an array used in initialization (or something that produces an array from a Numpy constructor) has ndim >= 2.
2. `Frame` now explicitly fails if an array used in initialization (or something that produces an array from a Numpy constructor) has ndim >= 3.

This ensures that the case shown above does not complete initialization without error. However, I am still exploring if `iterable_to_array` should identify this case and return an object type array automatically. There is a workaround now that if the  `Series` constructor is given `dtype=object` the expected 1D array is created.
